@PetHotel_HostAddress = http://localhost:5065
@token = CfDJ8PYGwwICNxZGmVW5uHcmSkc4Cp4hNOBByuzTKBNYSogVc7Yp9wkAlEognDt8nRKKCEflk0toHbWo7TWPcqBmRkN0f4XZNI85uw9ihw2YyJ4N1YRxfEL7X4cal2QRhaeWV7vNLtEXrKLfJ1BqMcMrBYhYpBhN3ZS6Dn1wxDAvMfquCAwChKZ8twmPDrXFsTyb05vWSPviUg72VV5-DNNX0Uu00UFyk9XNanZVvHJaS3wNX42bjgWMIZzSWtk0X-waCqqmelm29og8bHxq0DQJDl_8CbiJTDQoFOwYGK3f3hSJWIacIuykKEZwRvybMHmjU4Qiak3TjHokLEz51ccLYTI6CWSTqF_IknuO7SNewbV00Z2ILxDjYtwtjhxgZRgAtw8J2kWFw9UorE1YcWc25sfYim9c72-yjqFtZa0D2iBPgi8qbteJmyVeRhKQx4rhHdR94YVeQc-mW569lfnyRU13-nW0UKR8oZ1b2OjrV0Pl0RDM9G1jkQbqnQJvr9TKX34KU0rPVE0OovVf-oAPtZtefwtu9Bwj9vl5swclvAt8a8nVPxfGVc9oXhm8V4CGNB2OsNfkfvogHiKgc6VX4o8ZxMrBmuMDX6HRTONuJOXa07hdZ5GdIKFrEz0tQ6XvVwj-TYZI670iq0ckmCYF6Wbc_5URDCOxnR1r9IWKDxGCfmEs-IW6SYcz7QzPuLmwIA

###

GET {{PetHotel_HostAddress}}/api/hotels
Authorization: Bearer {{token}}


###
POST {{PetHotel_HostAddress}}/api/animals
Content-Type: application/json
{
    "Name" : "Ganja",
    "Spiecies" : "Dog",
    "Breed" : "Mongrel",
    "Age" : "5",
    "Weight" : 10
}
###
POST {{PetHotel_HostAddress}}/api/identity/login
Content-Type: application/json
{
   "email" : "test2@test.pl",
   "password" : "Password1!"
}